feat: Making outdated version warning more visible
apify/apify-cli pull request #301
Opened 2022-11-25 15:31 UTC by mtrunkat

2022-11-25 15:49 UTC, mtrunkat commented
Adding @mhamas as you recently did some changes in CLI

2022-11-29 10:03 UTC, drobnikj commented
I agree with Franta. Maybe we can hardcode frequently warning for versions <0.8 (or the version where the storage folder changed).

2022-12-09 12:06 UTC, mhamas commented
@mtrunkat what about this PR?

2022-12-20 09:16 UTC, mtrunkat commented
@mhamas @drobnikj @fnesveda fixed

2022-12-20 12:43 UTC, fnesveda requested changes
Much better, but this is still slowing down the start of every command noticeably (by ~200 ms) on my laptop, because of the many imports done from `utils.js`. Maybe it would be better to split this logic into a separate file, which does not require anything extra, and use dynamic imports wherever possible there, to speed up the most common scenario (package is up-to-date / the check is cached).

Also, it would be nice to run this in a `postinstall` script, so that the latest version is cached right from the start, and the first invocation of `apify` is really fast, that would be good for UX.

2022-12-20 12:43 UTC, fnesveda commented on src/lib/utils.js
>   * Check'll run approximately every 10. call
```suggestion
 * Check results will be cached for 24 hours
```

2022-12-22 11:09 UTC, mtrunkat commented
Thanks @fnesveda , good points.

2022-12-22 11:20 UTC, fnesveda requested changes
Much faster now, thanks!

I think you didn't regenerate the manifest after you added the `check-version` command, so it doesn't work for me right now.

2022-12-22 11:20 UTC, fnesveda commented on src/commands/check-version.js
> +    'enfore-update': flagsHelper.boolean({
Small typo:
```suggestion
        checkLatestVersion(flags.enforceUpdate);
    }
}

CheckVersionCommand.description = 'Checks that installed Apify CLI version is up to date.';

CheckVersionCommand.flags = {
    'enforce-update': flagsHelper.boolean({
```

2022-12-22 14:06 UTC, mtrunkat commented
I did not realized I need to run it after the command is added, done.

2022-12-22 14:07 UTC, fnesveda approved these changes

2022-12-27 11:02 UTC, drobnikj approved these changes
It looks like tests for win are still failing otherwise it looks good.

2022-12-30 09:15 UTC, merged