feat(app): Open actor detail after successful apify push
apify/apify-cli pull request #353
Opened 2023-03-30 11:36 UTC by HonzaTuron

Prompting user if want to open actor detail in browser after push

@dodaniel Feel free to update/suggest copy.

2023-03-30 11:43 UTC, fnesveda requested changes

2023-03-30 11:43 UTC, fnesveda commented on src/commands/push.js
> +            open(`https://console.apify.com/actors/${build.actId}`);
This will not work when the user is logged in as an organization, you'll have to add the `/organization/<USER-ID>` to the URL in that case.

2023-03-30 11:43 UTC, fnesveda commented on src/commands/push.js
> +            { type: 'confirm', name: 'continue', message: 'Do you want to open build detail in your browser?', default: true },
```suggestion
            { type: 'confirm', name: 'continue', message: 'Do you want to open the actor detail in your browser?', default: true },
```

2023-03-30 11:43 UTC, fnesveda commented on src/commands/push.js
> +            open(`https://console.apify.com/actors/${build.actId}`);
I see that this is the case also for the link at line 157, so we should adjust it there.

2023-04-03 09:38 UTC, fnesveda approved these changes

2023-04-03 11:19 UTC, nguyeda1 approved these changes

2023-04-03 11:38 UTC, merged